console.log("My First Console Project");
var first_name="Ranbir";
var last_name="Kapoor";
console.log(f_name.concat(l_name));
var a = 10;
var b = 5;
var add = a + b;
console.log(add);
var subtract = a - b;
console.log(subtract);
